import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Rocket from '@/components/Rocket'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <div className="overflow-hidden min-w-full h-screen relative">
          <div className="flex items-center justify-center h-1/4 bg-gray700 gap-3">
            <Rocket />
            <div>
              <span className="text-blue text-40 font-black">to</span>
              <span className="text-purpleDark text-40 font-black">do</span>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
